### ISSUE TITLE
Missing a file

### ISSUE THREAD

**Issue by gabribisto** [jabrell/pyeutl#9]
Hello, I'm trying to setup the scraper but I'm missing file "mapping" as shows the picture attached. Thank you
<img width="993" alt="Screenshot 2024-02-20 at 21 27 07" src="https://github.com/jabrell/pyeutl/assets/161821357/b564599b-de25-4587-a593-2d891b6306b0">

**Comment by jabrell** [comment]
Hi, it seems that this is related to scraping the data. That is another repository: https://github.com/jabrell/eutl_scraper Can please open an issue there and also post the code to replicate the error. My guess in the first would be that you try to scrape the transactions which has been depreciated since the EU commission annually releases a file with the transactions.
